export const EXTERNAL_LINKS = {
    prodEnv: "https://client.greenlake.hpe.com",
    integrationEnv: "https://client.greenlake.hpe.com",
    mailTo: "mailto:hpe-df@hpe.com"
}

export const BACKEND_STATUSES = {
    OK: "OK",
    ERROR: "ERROR"
}

export const DISALLOWED_EMAIL_DOMAINS = {
    "aol.com": null,
    "gmail.com": null,
    "googlemail.com": null,
    "icloud.com": null,
    "myyahoo.com": null,
    "yahoo.ae": null,
    "yahoo.at": null,
    "yahoo.be": null,
    "yahoo.ca": null,
    "yahoo.co.id": null,
    "yahoo.co.il": null,
    "yahoo.co.in": null,
    "yahoo.co.jp": null,
    "yahoo.co.nz": null,
    "yahoo.co.th": null,
    "yahoo.co.uk": null,
    "yahoo.co.za": null,
    "yahoo.com": null,
    "yahoo.com.ar": null,
    "yahoo.com.au": null,
    "yahoo.com.br": null,
    "yahoo.com.co": null,
    "yahoo.com.hk": null,
    "yahoo.com.hr": null,
    "yahoo.com.mx": null,
    "yahoo.com.my": null,
    "yahoo.com.ph": null,
    "yahoo.com.sg": null,
    "yahoo.com.tr": null,
    "yahoo.com.tw": null,
    "yahoo.com.vn": null,
    "yahoo.ch": null,
    "yahoo.cz": null,
    "yahoo.de": null,
    "yahoo.dk": null,
    "yahoo.es": null,
    "yahoo.fi": null,
    "yahoo.fr": null,
    "yahoo.gr": null,
    "yahoo.hu": null,
    "yahoo.ie": null,
    "yahoo.in": null,
    "yahoo.it": null,
    "yahoo.nl": null,
    "yahoo.no": null,
    "yahoo.pl": null,
    "yahoo.pt": null,
    "yahoo.ro": null,
    "yahoo.ru": null,
    "yahoo.se": null,
    "ymail.com": null
};
